spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  application:
    name: bookRecommendationApp
app:
  scheme: http
  host: localhost:8080
  client: localhost:5173
  constants:
    security:
      jwt-valid-hours: 72
      jwt-cookie-valid-hours: 72